name: Assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - cartopy>=0.21
  - jupyterlab
  - ipywidgets
  - rasterio
  - pyepsg
  - folium
  - matplotlib
  - numpy
  - shapely
  - rasterstats
  - seaborn
  - earthaccess
  - pyproj
